[project]
name = "flaskr"
version = "1.0.0"
description = "The workout tracker project to hone my Flask skills."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"